$main_monitor=desc:ASUSTek COMPUTER INC PG32UCDM S3LMQS098656
#$main_monitor=desc:Ancor Communications Inc ROG PG279Q #ASOXQTrVqobd
$side_monitor=desc:Ancor Communications Inc ROG PG279Q #ASOXQTrVqobd
#$old_side_monitor=desc: Samsung Electric Company SMS23A550H 0x30303535
